export const ActionTypes = {
  SET_PRODUCTS_SUCCESS: "SET_PRODUCTS_SUCCESS",
  SET_PRODUCTS_FAILD: "SET_PRODUCTS_FAILD",
  SET_PRODUCT_REQUESTED: "SET_PRODUCT_REQUESTED",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
};
